export const types = {
  //AUTH ACTIONS//
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  CREATE_PROFILE_START: "CREATE_PROFILE_START",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAIL: "CREATE_PROFILE_FAIL",

  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",

  GET_USER_START: "GET_USER_START",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAIL: "GET_USER_FAIL",

  WELCOME_BACK: "WELCOME_BACK",
  //AUTH ACTIONS//

  //CRUD ACTIONS//
  GET_START: "GET_START",
  GET_SUCCESS: "GET_SUCCESS",
  GET_FAIL: "GET_FAIL",

  POST_START: "POST_START",
  POST_SUCCESS: "POST_SUCCESS",
  POST_FAIL: "POST_FAIL",

  PUT_ITEM_START: "PUT_ITEM_START",
  PUT_ITEM_SUCCESS: "PUT_ITEM_SUCCESS",
  PUT_ITEM_FAIL: "PUT_ITEM_FAIL",

  DELETE_START: "DELETE_START",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAIL: "DELETE_FAIL"
  //CRUD ACTIONS//
};
